version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: codeconnect
    volumes:
      - postgres_data:/var/lib/postgresql/data

  codeconnect:
    image: ${DOCKER_REGISTRY-}codeconnect
    build:
      context: .
      dockerfile: CodeConnect/Dockerfile
    ports:
      - "5259" 