version: '3.4'

services:
  db:
    hostname: database
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: codeconnect
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    hostname: codeconnect
    image: ${DOCKER_REGISTRY-}codeconnect
    build:
      context: .
      dockerfile: CodeConnect/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./CodeConnect/wwwroot/images:/app/wwwroot/images

  frontend:
    hostname: frontend
    build: codeconnect_frontend
    depends_on: 
      - api

  caddy:
    hostname: caddy
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - '80:80'
    depends_on:
      - frontend
      - api